

[workspace]
members = [
    "sys",
    "gdnative",
    "geom",
    "test",
    "examples/dodge-the-creeps",
    "examples/hello_world",
    "examples/spinning_cube",
    "examples/manually_registered",
]
